// <auto-generated />
using System;
using Loan_API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loan_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Loan_API.Entities.CustommerContact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AlternativePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerCity")
                        .HasColumnType("int");

                    b.Property<int>("PerState")
                        .HasColumnType("int");

                    b.Property<string>("PerStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerZIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PreCity")
                        .HasColumnType("int");

                    b.Property<int>("PreState")
                        .HasColumnType("int");

                    b.Property<string>("PreStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreZIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustommerContact");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerEmployment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("EmployerOrBusnContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerOrBusnName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleOrBusnType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MonthlyIncOrBusnRev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkOrBusnAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExpOrBusnAge")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustommerEmployment");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerFinancialInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetsOwned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Liabilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncomeSources")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustommerFinancialInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerGuarantorDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("GuarantorAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorNationalIDOrPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithApplicant")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustommerGuarantorDetails");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerIdentificatio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("DrivingLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIDOrPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustommerIdentificatio");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerPersonnelInfo", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CustCardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustommerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustommerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("CustommerPersonnelInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerContact", b =>
                {
                    b.HasOne("Loan_API.Entities.CustommerPersonnelInfo", "CustommerPersonnelInfo")
                        .WithOne("CustommerContact")
                        .HasForeignKey("Loan_API.Entities.CustommerContact", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustommerPersonnelInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerEmployment", b =>
                {
                    b.HasOne("Loan_API.Entities.CustommerPersonnelInfo", "CustommerPersonnelInfo")
                        .WithOne("CustommerEmployment")
                        .HasForeignKey("Loan_API.Entities.CustommerEmployment", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustommerPersonnelInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerFinancialInfo", b =>
                {
                    b.HasOne("Loan_API.Entities.CustommerPersonnelInfo", "CustommerPersonnelInfo")
                        .WithOne("CustommerFinancialInfo")
                        .HasForeignKey("Loan_API.Entities.CustommerFinancialInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustommerPersonnelInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerGuarantorDetails", b =>
                {
                    b.HasOne("Loan_API.Entities.CustommerPersonnelInfo", "CustommerPersonnelInfo")
                        .WithOne("CustommerGuarantorDetails")
                        .HasForeignKey("Loan_API.Entities.CustommerGuarantorDetails", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustommerPersonnelInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerIdentificatio", b =>
                {
                    b.HasOne("Loan_API.Entities.CustommerPersonnelInfo", "CustommerPersonnelInfo")
                        .WithOne("CustommerIdentificatio")
                        .HasForeignKey("Loan_API.Entities.CustommerIdentificatio", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustommerPersonnelInfo");
                });

            modelBuilder.Entity("Loan_API.Entities.CustommerPersonnelInfo", b =>
                {
                    b.Navigation("CustommerContact");

                    b.Navigation("CustommerEmployment");

                    b.Navigation("CustommerFinancialInfo");

                    b.Navigation("CustommerGuarantorDetails");

                    b.Navigation("CustommerIdentificatio");
                });
#pragma warning restore 612, 618
        }
    }
}
