name: Auto Deploy to Local IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      IIS_PATH: 'C:\inetpub\wwwroot\loan-api'
      APP_POOL: "LoanApiPool"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Loan-API.sln

      - name: Build
        run: dotnet build Loan-API.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Loan-API/Loan-API.csproj -c Release -o publish

      - name: Stop IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "${{ env.APP_POOL }}"

      - name: Clean IIS Folder
        shell: powershell
        run: |
          if (Test-Path "${{ env.IIS_PATH }}") {
            Remove-Item "${{ env.IIS_PATH }}\*" -Recurse -Force
          }

      - name: Copy Files
        shell: powershell
        run: |
          Copy-Item "publish\*" -Destination "${{ env.IIS_PATH }}" -Recurse -Force

      - name: Start IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "${{ env.APP_POOL }}"