name: Auto Deploy to Local IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      IIS_PATH: 'C:\inetpub\wwwroot\loan-api'
      APP_POOL: "LoanApiPool"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Loan-API.sln

      - name: Build
        run: dotnet build Loan-API.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Loan-API/Loan-API.csproj -c Release -o publish

      # =========================
      # STOP IIS APP POOL (SAFE)
      # =========================
      - name: Stop IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration

          $pool = "${{ env.APP_POOL }}"

          if ((Get-WebAppPoolState $pool -ErrorAction SilentlyContinue).Value -eq "Started") {
              Stop-WebAppPool -Name $pool
          } else {
              Write-Host "App Pool already stopped or not found, skipping stop."
          }

      # =========================
      # CLEAN FOLDER (SAFE)
      # =========================
      - name: Clean IIS Folder
        shell: powershell
        run: |
          $path = "${{ env.IIS_PATH }}"

          if (Test-Path $path) {
              Remove-Item "$path\*" -Recurse -Force -ErrorAction SilentlyContinue
          }

      # =========================
      # COPY FILES (ROBUST FIX)
      # =========================
      - name: Copy Files
        shell: powershell
        run: |
          robocopy publish "${{ env.IIS_PATH }}" /MIR

          if ($LASTEXITCODE -le 7) {
              exit 0
          } else {
              exit $LASTEXITCODE
          }
      # =========================
      # START IIS APP POOL (SAFE)
      # =========================
      - name: Start IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration

          $pool = "${{ env.APP_POOL }}"

          if ((Get-WebAppPoolState $pool -ErrorAction SilentlyContinue).Value -eq "Stopped") {
              Start-WebAppPool -Name $pool
          } else {
              Write-Host "App Pool already running or not found."
          }